const PipelineEvents = {
    LIBRARY_SCANNED: 'LIBRARY_SCANNED',
    ASSETS_SELECTED: 'ASSETS_SELECTED',
    LAYOUT_GENERATED: 'LAYOUT_GENERATED',
    DURATION_PREPARED: 'DURATION_PREPARED',
    VARIATION_GENERATED: 'VARIATION_GENERATED',
    STORY_DECIDED: 'STORY_DECIDED',
    TIMELINE_BUILT: 'TIMELINE_BUILT',
    RECIPE_BUILT: 'RECIPE_BUILT',
    RECIPE_VALIDATED: 'RECIPE_VALIDATED',
    FFMPEG_BUILT: 'FFMPEG_BUILT',
    RENDER_QUEUED: 'RENDER_QUEUED',
    RENDER_STARTED: 'RENDER_STARTED',
    RENDER_PROGRESS: 'RENDER_PROGRESS',
    RENDER_FINISHED: 'RENDER_FINISHED',
    MANIFEST_GENERATED: 'MANIFEST_GENERATED',
    HISTORY_SAVED: 'HISTORY_SAVED',
    RENDER_FAILED: 'RENDER_FAILED'
};

const EventEmitter = require('events');
class PipelineEmitter extends EventEmitter {}

module.exports = {
    PipelineEvents,
    PipelineEmitter: new PipelineEmitter()
};
