export const ReactivePresets = {
    zoom_pulse_default: {
        id: 'zoom_pulse_default',
        version: 1,
        name: 'Zoom Pulse',
        description: 'Professional beat synchronized zoom effect.',
        category: 'Scale',
        recommendedGenre: 'Universal',
        effect: 'Zoom Pulse',
        source: 'kick',
        amplitude: 15,
        threshold: 40,
        attack: 5,
        release: 150,
        smoothness: 15,
        curve: 'easeOut',
        operation: 'multiply',
        defaultEnabled: true
    },
    camera_shake_default: {
        id: 'camera_shake_default',
        version: 1,
        name: 'Camera Shake',
        description: 'Cinematic bass rumble for heavy impacts.',
        category: 'Camera',
        recommendedGenre: 'Universal',
        effect: 'Camera Shake',
        source: 'bass',
        amplitude: 40,
        threshold: 50,
        attack: 20,
        release: 300,
        smoothness: 40,
        curve: 'easeOut',
        operation: 'multiply',
        defaultEnabled: true
    },
    beat_flash_default: {
        id: 'beat_flash_default',
        version: 1,
        name: 'Beat Flash',
        description: 'Sharp strobe effect on transients.',
        category: 'Flash',
        recommendedGenre: 'Universal',
        effect: 'Beat Flash',
        source: 'beat',
        amplitude: 60,
        threshold: 60,
        attack: 0,
        release: 100,
        smoothness: 0,
        curve: 'impulse',
        operation: 'multiply',
        defaultEnabled: true
    },
    bg_pulse_default: {
        id: 'bg_pulse_default',
        version: 1,
        name: 'Background Pulse',
        description: 'Ambient track breathing effect.',
        category: 'Background',
        recommendedGenre: 'Ambient',
        effect: 'Brightness Pulse',
        source: 'energy',
        amplitude: 20,
        threshold: 20,
        attack: 50,
        release: 300,
        smoothness: 70,
        curve: 'easeInOut',
        operation: 'multiply',
        defaultEnabled: true
    },
    logo_pulse_default: {
        id: 'logo_pulse_default',
        version: 1,
        name: 'Logo Pulse',
        description: 'UI/Logo popping and locking.',
        category: 'Logo',
        recommendedGenre: 'Universal',
        effect: 'Scale Pulse',
        source: 'beatStrength',
        amplitude: 25,
        threshold: 40,
        attack: 15,
        release: 200,
        smoothness: 30,
        curve: 'easeOut',
        operation: 'multiply',
        defaultEnabled: true
    },
    brightness_pulse_default: {
        id: 'brightness_pulse_default',
        version: 1,
        name: 'Brightness Pulse',
        description: 'Universal rhythmic glow mapping to track energy.',
        category: 'Brightness',
        recommendedGenre: 'Universal',
        effect: 'Brightness Pulse',
        source: 'energy',
        amplitude: 30,
        threshold: 30,
        attack: 20,
        release: 150,
        smoothness: 20,
        curve: 'easeOut',
        operation: 'multiply',
        defaultEnabled: true
    },
    scale_pulse_default: {
        id: 'scale_pulse_default',
        version: 1,
        name: 'Scale Pulse',
        description: 'Safe-margin gentle swelling.',
        category: 'Scale',
        recommendedGenre: 'Ambient',
        effect: 'Scale Pulse',
        source: 'energy',
        amplitude: 10,
        threshold: 10,
        attack: 40,
        release: 200,
        smoothness: 50,
        curve: 'easeInOut',
        operation: 'multiply',
        defaultEnabled: true
    }
};
