const defaultNewProps = {
  eqBands: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  removeLowRumble: false,
  removeHum: false,
  tightenBass: false,
  removeHiss: false,
  loudnessDrive: 0,
  headphoneComfort: 0,
  lrBalance: 0,
  clarity: 0,
  warmth: 0,
  punch: 0,
  deEsser: 0,
  glueDensity: 0,
  spatial8D: 0,
  lofiNoise: 0,
  reverb: 0,
  tapeFlutter: 0,
  bitcrush: 0
};

export const MASTERING_PROFILES = [
  {
    id: 'neutral',
    name: 'Standard (Neutral)',
    targetLufs: -14,
    limiter: true,
    compressor: false,
    stereoWidth: 100,
    outputGain: '0',
    ...defaultNewProps
  },
  {
    id: 'edm',
    name: 'EDM / Electronic',
    targetLufs: -9,
    limiter: true,
    compressor: true,
    stereoWidth: 120,
    outputGain: '1.5',
    ...defaultNewProps,
    eqBands: [3, 4, 2, 0, -1, 0, 1, 2, 3, 4],
    punch: 80,
    clarity: 60,
    loudnessDrive: 3.5,
    glueDensity: 70
  },

  {
    id: 'phonk',
    name: 'Phonk / Drift',
    targetLufs: -8,
    limiter: true,
    compressor: true,
    stereoWidth: 110,
    outputGain: '2',
    ...defaultNewProps,
    eqBands: [5, 6, 4, 1, -2, 0, 1, 2, 4, 3],
    punch: 100,
    loudnessDrive: 6.0,
    glueDensity: 90,
    tightenBass: true
  },
  {
    id: 'pop',
    name: 'Pop / Top 40',
    targetLufs: -11,
    limiter: true,
    compressor: true,
    stereoWidth: 105,
    outputGain: '0',
    ...defaultNewProps,
    eqBands: [1, 1, 0, -1, 0, 2, 3, 4, 3, 2],
    clarity: 75,
    punch: 40,
    glueDensity: 50,
    deEsser: 30
  },
  {
    id: 'hiphop',
    name: 'Hip Hop / Rap',
    targetLufs: -10,
    limiter: true,
    compressor: true,
    stereoWidth: 100,
    outputGain: '1',
    ...defaultNewProps,
    eqBands: [4, 5, 2, -1, -1, 1, 2, 3, 2, 1],
    punch: 90,
    tightenBass: true,
    glueDensity: 60
  },
  {
    id: 'synthwave',
    name: 'Synthwave / Retro',
    targetLufs: -12,
    limiter: true,
    compressor: true,
    stereoWidth: 130,
    outputGain: '0.5',
    ...defaultNewProps,
    eqBands: [2, 2, 1, 0, 0, 1, 2, 3, 4, 2],
    clarity: 60,
    warmth: 40,
    spatial8D: 20,
    reverb: 35
  },
  {
    id: 'cinematic',
    name: 'Cinematic / Epic',
    targetLufs: -14,
    limiter: true,
    compressor: false,
    stereoWidth: 140,
    outputGain: '0',
    ...defaultNewProps,
    eqBands: [3, 2, 0, 0, 0, 0, 1, 2, 3, 2],
    spatial8D: 40,
    clarity: 50,
    warmth: 30,
    removeLowRumble: true,
    reverb: 50
  },
  {
    id: 'acoustic',
    name: 'Acoustic / Indie',
    targetLufs: -14,
    limiter: true,
    compressor: false,
    stereoWidth: 100,
    outputGain: '0',
    ...defaultNewProps,
    eqBands: [0, 1, 2, 1, 0, 0, 1, 2, 1, 0],
    warmth: 60,
    clarity: 50
  },
  {
    id: 'ambient',
    name: 'Classical / Ambient',
    targetLufs: -16,
    limiter: false,
    compressor: false,
    stereoWidth: 110,
    outputGain: '0',
    ...defaultNewProps,
    eqBands: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    spatial8D: 50,
    headphoneComfort: 60
  },
  {
    id: 'podcast',
    name: 'Podcast / Voice',
    targetLufs: -16,
    limiter: true,
    compressor: true,
    stereoWidth: 90,
    outputGain: '0',
    ...defaultNewProps,
    eqBands: [-4, -2, 1, 2, 3, 4, 2, 0, -1, -2],
    removeLowRumble: true,
    removeHum: true,
    deEsser: 80,
    clarity: 90
  },
  {
    id: 'dangdut',
    name: 'Dangdut / Koplo',
    targetLufs: -10,
    limiter: true,
    compressor: true,
    stereoWidth: 105,
    outputGain: '1',
    ...defaultNewProps,
    eqBands: [3, 4, 1, -1, 1, 3, 4, 3, 2, 1],
    punch: 70,
    clarity: 80,
    glueDensity: 50,
    tightenBass: true
  },
  {
    id: 'djslow',
    name: 'DJ Slow (TikTok)',
    targetLufs: -9,
    limiter: true,
    compressor: true,
    stereoWidth: 125,
    outputGain: '1.5',
    ...defaultNewProps,
    eqBands: [6, 7, 3, 0, -1, 0, 2, 4, 5, 4],
    punch: 100,
    clarity: 70,
    loudnessDrive: 4.5,
    glueDensity: 85,
    tightenBass: true,
    spatial8D: 10
  },
  {
    id: 'rock',
    name: 'Rock / Metal',
    targetLufs: -9,
    limiter: true,
    compressor: true,
    stereoWidth: 110,
    outputGain: '1.5',
    ...defaultNewProps,
    eqBands: [4, 3, 1, -2, -3, -1, 2, 4, 5, 3],
    punch: 85,
    loudnessDrive: 4.0,
    glueDensity: 70
  },
  {
    id: 'rnb',
    name: 'R&B / Soul',
    targetLufs: -12,
    limiter: true,
    compressor: true,
    stereoWidth: 100,
    outputGain: '0.5',
    ...defaultNewProps,
    eqBands: [5, 4, 2, 1, 0, 0, 1, 2, 3, 2],
    warmth: 75,
    clarity: 60
  },
  {
    id: 'jazz',
    name: 'Jazz / Blues',
    targetLufs: -14,
    limiter: false,
    compressor: false,
    stereoWidth: 100,
    outputGain: '0',
    ...defaultNewProps,
    eqBands: [1, 2, 3, 2, 1, 0, 1, 1, 0, -1],
    warmth: 80,
    clarity: 50
  }
];

export function getDefaultMasteringSettings() {
  return { ...MASTERING_PROFILES[0] };
}
