import { EngineRegistry } from './EngineRegistry.js';
import './validators/BasicValidators.js';
import fs from 'fs/promises';
import path from 'path';

async function generateRoadmap() {
    const coverage = EngineRegistry.coverage();
    const stats = EngineRegistry.statistics();
    const validators = EngineRegistry.getValidators();

    let content = `# QA Toolkit Roadmap Status\n\n`;
    content += `## Overview\n`;
    content += `- **Total Expected Engines:** ${coverage.totalExpected}\n`;
    content += `- **Implemented Validators:** ${coverage.implemented}\n`;
    content += `- **Missing Validators:** ${coverage.missing}\n`;
    content += `- **Coverage:** ${coverage.percentage}%\n\n`;

    content += `## Category Breakdown\n`;
    for (const [cat, count] of Object.entries(stats.byCategory)) {
        content += `- **${cat}:** ${count}\n`;
    }

    content += `\n## Engine Status\n`;
    validators.forEach(v => {
        content += `### ${v.engineName}\n`;
        content += `- Category: ${v.category || 'Core'}\n`;
        content += `- Description: ${v.description || 'NOT IMPLEMENTED'}\n`;
        content += `- Version: ${v.version || 'NOT IMPLEMENTED'}\n`;
        content += `- Dependencies: ${v.dependencies ? v.dependencies.join(', ') : 'None'}\n\n`;
    });

    content += `\n*Auto-generated by Production QA Toolkit Framework Lock*\n`;

    const outPath = path.resolve(process.cwd(), 'ROADMAP_STATUS.md');
    await fs.writeFile(outPath, content, 'utf8');
    console.log(`Generated ROADMAP_STATUS.md at ${outPath}`);
}

generateRoadmap().catch(console.error);
